name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.3"

    - name: Cache python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run the script
      env:
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASS: ${{ secrets.MONGO_PASS }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python main.py
